
DROP TABLE IF EXISTS operation;
DROP TABLE IF EXISTS deposite;
DROP TABLE IF EXISTS account;

create table if not exists account
(
    id bigint generated by default as identity,
    login varchar(255) not null unique,
    pinCode varchar(255) not null,
    primary key (id)
);

create table if not exists deposite
(
    id bigint generated by default as identity,
    owner_id        bigint not null,
    type 			varchar(255) check (type in ('RUB')),
    amount_money     numeric(38,2),
    created 		bigint,
    primary key (id)
);

create table if not exists operation
(
	id bigint generated by default as identity,
    amount numeric(38,2),
    created bigint,
    payer_id bigint,
    recipient_id bigint,
    type varchar(255) check (type in ('WITHDRAW','TRANSFER','REPLENISHMENT')),
    primary key (id)
);
alter table if exists deposite add constraint FKca20xp4qp4kucbhjgld1hy7f8 foreign key (owner_id) references account;
alter table if exists operation add constraint FKh1hnw6pv899bx05ghkq3833kg foreign key (payer_id) references deposite;
alter table if exists operation add constraint FKkut6xupnrt8y12hy11eifr4pl foreign key (recipient_id) references deposite;
